repos:
  - repo: http://raspberrypi:3000/cswartz/custom-precommit-hooks.git
    rev: v0.2
    hooks:
      - id: check-ast
        exclude: templates/.*
      - id: check-case-conflict
      - id: check-yaml
      - id: check-json
        exclude: .vscode/.*
      - id: check-toml
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
      - id: mypy
